services:
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    volumes:
      - ../../prometheus/config:/etc/prometheus
      - ../../prometheus/volume:/prometheus
    depends_on:
      - grafana
    ports:
      - 9090:9090
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
      - '--storage.tsdb.retention.time=7d'
    environment:
      - TZ=Asia/Seoul
    logging:
      driver: 'json-file'
      options:
        max-size: '8m'
        max-file: '10'
    restart: always
    networks:
      - server

  node-exporter:
    image: prom/node-exporter
    volumes:
      - ../../proc:/host/proc:ro
      - ../../sys:/host/sys:ro
      - ../../:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - --collector.filesystem.ignored-mount-points
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - 9100:9100
    deploy:
      mode: global
    restart: always
    networks:
      - server

  loki:
    # https://github.com/grafana/loki/issues/5513
    # 1. dockerfile
    # 2. 다른 방안
    user: root
    container_name: loki
    image: grafana/loki:latest
    volumes:
      - ../../loki/config:/loki
      - ../../loki/volume:/loki
    ports:
      - 3100:3100
      - 9096:9096
    restart: always
    networks:
      - server

  # tempo:
  #   container_name: tempo
  #   image: grafana/tempo:latest
  #   command:
  #     ['-config.file=/tmp/tempo/config/tempo.yaml', '--auth.enabled=false']
  #   volumes:
  #     - ../../tempo/config:/tmp/tempo/config
  #     - ../../tempo/volume:/tmp/tempo
  #   depends_on:
  #     - grafana
  #     - prometheus
  #   ports:
  #     - '3200:3200' # tempo
  #     - '9095:9095' # tempo grpc
  #     - '4317:4317' # otlp grpc
  #     - '4318:4318' # otlp http
  #   restart: always
  #   networks:
  #     - server

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    ports:
      - 9080:9080
    volumes:
      - ../../promtail/config:/promtail/config
      - ../../promtail/volume:/promtail
      - ../../logs:/promtail/logs/code
      - ../../db/mysql/logs:/promtail/logs/mysql
      - ../../db/redis/logs:/promtail/logs/redis
    command: -config.file=/promtail/config/config.yaml
    depends_on:
      - grafana
      - prometheus
    restart: always
    networks:
      - server

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - TZ=Asia/Seoul
    ports:
      - 3005:3005
    volumes:
      - ../../grafana/volume:/var/lib/grafana
      - ../../grafana/config/grafana.ini:/etc/grafana/grafana.ini:ro
    restart: always
    networks:
      - server
networks:
  server:
    driver: bridge
    external: true
