server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /promtail/config/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    headers:
      X-Scope-OrgID: monitoring

target_config:
  sync_period: 10s

scrape_configs:
  - job_name: code-logs
    static_configs:
      - targets:
          - localhost
        labels:
          application: code
          env: local
          __path__: /promtail/logs/code/*.log.*
    relabel_configs:
      - source_labels: ['__codelabel__']
        target_label: codelabel
  - job_name: mysql-slow-logs
    static_configs:
      - targets:
          - localhost
        labels:
          application: mysql-slow
          env: local
          __path__: /promtail/logs/mysql/slow.log
    relabel_configs:
      - source_labels: ['__mysqlslow__']
        target_label: mysqlslowlabel
  - job_name: mysql-error-logs
    static_configs:
      - targets:
          - localhost
        labels:
          application: mysql-error
          env: local
          __path__: /promtail/logs/mysql/error.log
    relabel_configs:
      - source_labels: ['__mysqlerror__']
        target_label: mysqlerrorlabel
  - job_name: redis
    static_configs:
      - targets:
          - localhost
        labels:
          application: redis
          env: local
          __path__: /promtail/logs/redis/redis.log
    relabel_configs:
      - source_labels: ['__redis__']
        target_label: redis
